## Case-insensitive
blocked-words:
  - wOrdS
  - To
  - bE
  - bLOcKed

## if the punish-type is set to BAN, the ban-duration will be used
punish-type: WARN

## (s = seconds, m = minutes, h = hours, d = days)
ban-duration: 1h 

## message displayed when player gets banned
ban-message: You have been banned from the server for saying a blocked word.

## message displayed when player gets kicked
kick-message: You have been kicked from the server for saying a blocked word.